name: pioneer-writers

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t allanbinga/murandi-backend:v1.0.0 .
          docker push allanbinga/murandi-backend:v1.0.0

      - name: Build and push frontend image
        run: |
          docker build \
            --build-arg VITE_BACKEND_ENDPOINT=${{ secrets.VITE_BACKEND_ENDPOINT }} \
            --build-arg VITE_APP_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_APP_STRIPE_PUBLISHABLE_KEY }} \
            -t allanbinga/murandi-frontend:v1.0.0 ./client
          docker push allanbinga/murandi-frontend:v1.0.0